### ISSUE TITLE
error NameError: name 'video_main_function' is not defined

### ISSUE THREAD

**Issue by Thrqureshi** [AkshitIreddy/AI-Powered-Video-Tutorial-Generator#1]
I am a beginner to python and NodeJS

when I am running this app. I am getting this error

NameError: name 'video_main_function' is not defined 

on a backend terminal, I am getting this 

INFO:     Started server process [9272]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:52834 - "GET /videoCreate HTTP/1.1" 405 Method Not Allowed

Any idea why I am getting these error

**Comment by AkshitIreddy** [comment]
oh i made a mistake, in main.py video_main_function was supposed to be video_main, i fixed the bug, you can try again by cloning or go to main.py and and rename video_main_function to video_main in line 30 path = ...
