### ISSUE TITLE
SadTalker installation

### ISSUE THREAD

**Issue by tendiesman** [AkshitIreddy/AI-Powered-Video-Tutorial-Generator#2]
For the SadTalker installation do we have to install everything and run everything from the SadTalker conda environment?

Or can we just clone SadTalker and then run from the venv we made earlier?

Thanks in advance

**Comment by AkshitIreddy** [comment]
You'll need to follow these instructions and make sure that venv is created and present within sadtalker dir
Install ffmpeg, following [this instruction](https://www.wikihow.com/Install-FFmpeg-on-Windows) (OR using scoop install ffmpeg via [scoop](https://scoop.sh/)).
Download the SadTalker repository, for example by running git clone https://github.com/Winfredy/SadTalker.git.
bash Sadtalker/scripts/download_models.sh
Run start.bat from Windows Explorer as normal, non-administrator, user, venv will be created within sadtalker dir

After venv is created you do not need to use it directly, continue using .venv , venv is used within the code over here so you don't have to manually activate it
https://github.com/AkshitIreddy/AI-Powered-Video-Tutorial-Generator/blob/main/backend/functions/create_video_from_audio_function.py/#L13-L21

**Comment by AkshitIreddy** [comment]
if you want to only use one environment, you should install everything in one environment and then modify this to use that environment
https://github.com/AkshitIreddy/AI-Powered-Video-Tutorial-Generator/blob/main/backend/functions/create_video_from_audio_function.py/#L13-L21
