### ISSUE TITLE
Cohere model not found

### ISSUE THREAD

**Issue by patrickbatesman** [AkshitIreddy/AI-Powered-Video-Tutorial-Generator#3]
recently saw your project and i am pretty intrested in that, i tried running it i successfully ran the webui for sadtalker and the frontend part for this project is running good i am facing some issues running the backend

i got my trial_api keys and i added it into the ```apikeys.json``` file
```json
{
    "api_keys": [
        "XXXXXXXXXXXXXXXX"
     ]
}
```

i am facing this error while running the backend saying that:
```
cohere.error.CohereAPIError: model not found, make sure the correct model ID was used and that you have access to the model.
```

please guide me through this as i am a pretty newbie to this field.

Thanks!!

**Comment by AkshitIreddy** [comment]
it's been a while since i made this project, in that time cohere may have changed model names, so try changing the model name to only "command" in line 28 backend/functions/create_script_function.py
    llm = Cohere(cohere_api_key=selected_key,
                 model='command-xlarge-beta', temperature=1.2, max_tokens=1700)
