### ISSUE TITLE
Api calls

### ISSUE THREAD

**Issue by Faizan960** [AkshitIreddy/AI-Powered-Video-Tutorial-Generator#6]
hey akshit, can you help me find the snippet of code where you have decided number of api calls of cohere as cohere has limited free api key toh 5 calls/per minute so am facing error through it

**Comment by AkshitIreddy** [comment]
https://github.com/AkshitIreddy/AI-Powered-Video-Tutorial-Generator/blob/main/backend/functions/create_script_function.py#L28-L43

**Comment by AkshitIreddy** [comment]
https://github.com/AkshitIreddy/AI-Powered-Video-Tutorial-Generator/blob/main/backend/functions/create_search_query_function.py#L13-L24

**Comment by AkshitIreddy** [comment]
this code is very old, so you might be getting error for different reasons

**Comment by AkshitIreddy** [comment]
https://github.com/AkshitIreddy/AI-Powered-Video-Tutorial-Generator/blob/main/backend/functions/create_audio_image_function.py#L21-L24
